### ISSUE TITLE
Output the display resolution

### ISSUE THREAD

**Issue by FlappyFalcon** [ekisu/mpv-webm#104]
Not necessarily an issue but is there a way to encode at the output res? Some old anime were mastered in a weird way that some fan-sub releases are anamorphic and have a storage resolution at like for example 704 x 480, but the file plays at the correct 704 x 528. Is there a way to encode to the latter? Say I want to encode to 480p (640 x 480), the script still keeps the storage resolution which I don't want. Is there anyway to stop that?

**Comment by Vzaa** [comment]
Hi @FlappyFalcon,

I think I stumbled into the same issue recently by coincidence. The "Force Square Pixels" option I added with the change below might be what you're looking for. I plan to put this in a PR soon

https://github.com/Vzaa/mpv-webm/commit/675e7bc655ac6ecd6139a2d382265d0c7bb43f02

If you'd like to check out a build:

> Add 'Force Square Pixels' option (Vzaa)
https://github.com/Vzaa/mpv-webm/releases

**Comment by FlappyFalcon** [comment]
Ooh, that sound does sound like what I'm looking for! I'll test it out on an anamorphic anime DVD when I get back from work
