### ISSUE TITLE
Option to encode muted video

### ISSUE THREAD

**Issue by ottersarecool** [ekisu/mpv-webm#114]
## mpv version and platform

Linux tyrus 5.12.6-arch1-1 #1 SMP PREEMPT Sun, 23 May 2021 00:45:50 +0000 x86_64 GNU/Linux
```
mpv 0.33.1-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.
```

## Description

I noticed that in the encode options a option to disable sound is missing, it would enhance the workflow of this handy little script.

**Comment by Vzaa** [comment]
If you mute on mpv itself by pressing m, and then the same option is passed for encoding.

**Comment by ottersarecool** [comment]
> If you mute on mpv itself by pressing m, then the same option is passed for encoding.

thank you!
