### ISSUE TITLE
no-input-default-bindings

### ISSUE THREAD

**Issue by Baz00ka69** [ekisu/mpv-webm#128]
Doesn't seem like this works if you have 

--no-input-default-bindings

I have tried changing the keybinding aswell.
Can anybody else confirm? Is there a fix?

**Comment by ekisu** [comment]
Yeah, using that makes keybinds added via scripting not work as well. You could use `no-default-builtin-bindings` instead, or add the following line to your `input.conf`:
```
W script-binding webm/display-webm-encoder
```
