### ISSUE TITLE
Feature Request: Remove audio/Video Only option 

### ISSUE THREAD

**Issue by Pentaphon** [ekisu/mpv-webm#129]
As the title says. It's useful for gif-type sites that are actually video.

**Comment by ekisu** [comment]
Muting the player before encoding should make it video-only... Not sure if it's worth having a dedicated option for that

**Comment by Pentaphon** [comment]
> Muting the player before encoding should make it video-only...

Confirmed. I didn't see that mentioned in the menu but you did put it in the readme and I just overlooked it.
