### ISSUE TITLE
Sub position not working

### ISSUE THREAD

**Issue by 2084x** [ekisu/mpv-webm#148]
## mpv version and platform

Arch Linux
```
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects 
 built on UNKNOWN 
FFmpeg library versions: 
   libavutil       57.17.100 (runtime 57.28.100) 
   libavcodec      59.18.100 (runtime 59.37.100) 
   libavformat     59.16.100 (runtime 59.27.100) 
   libswscale      6.4.100 (runtime 6.7.100) 
   libavfilter     8.24.100 (runtime 8.44.100) 
   libswresample   4.3.100 (runtime 4.7.100) 
FFmpeg version: n5.1.1 
```

## Description

When the subtitles position is changed, the script ignores this and always outputs it in the default position. This happens with internal subs, external sub files and also when streaming sub files (like with yt-dlp).

Is this the expected result of the script? can a change be made to respect the sub position?

Here's an example:

original video file with sub position changed to ~35/100:
![mpv-shot0001](https://user-images.githubusercontent.com/108906685/189245835-ed41022d-5b16-4d2b-9038-5e9e0c358df3.jpg)

encoded webm automatically puts it back to 100/100:
![mpv-shot0003](https://user-images.githubusercontent.com/108906685/189245911-ffc4a22f-6248-4293-8584-b5932207fdbb.jpg)

**Comment by oluladef** [comment]
It wasn't pulling the position from the player, added line
