### ISSUE TITLE
Not encoding

### ISSUE THREAD

**Issue by FlappyFalcon** [ekisu/mpv-webm#17]
Is there a limit on file size of a file that this plugin can encode from? It won't encode at all from, well, it says encoded successfully but no file.

**Comment by ElegantMonkey** [comment]
Please post logs. There's no limit, AFAIK.

**Comment by FlappyFalcon** [comment]
Sorry but where are the logs located? I wasn't aware it made a log after each encode. Well this won't even give a file, it just instantly says successfully encoded after pressing e. I think it's just buggy, because it works at different sections of the video but not at specific frame. weird

**Comment by macamaca2** [comment]
I downloaded this video from youtube with youtube-dl -f best https://www.youtube.com/watch?v=Zzq5PW5cyp0 . Set the start point to 0 and the endpoint almost at the end. Set audio on (works with audio off). Change the scale to 240 and the file size
 to 3800. When I press encode it immediately says successful but it outputs nothing.
[log.txt](https://github.com/ElegantMonkey/mpv-webm/files/1883441/log.txt)

**Comment by macamaca2** [comment]
I think what FlappyFalcon means by "not at a specific frame" is that it works on some videos when the section is like 00:10 to 00:20, but when you select 00:01 to 01:20 it fails. 00:10 to 00:20 actually works on the video I linked. But change it to 00:00 to 2:01 and it fails.

**Comment by ElegantMonkey** [comment]
@macamaca2
Looking at the logs, there's nothing really suspicious. I wished it printed the encoding command output (it usually does for me, but I guess it's because I use `log-file` on the config file, which causes the encoder to also output to the log).

Could you try running the encode command line (search for "Command line" on the log) separately and see what happens? (You'll need to escape the paths I think).

**Comment by macamaca2** [comment]
@ElegantMonkey 
When I run the command manually I get a few errors. I'm attaching a log file generated with log-file doing the original converting, and a log file piped from output doing the command manually.
[generated-with-log-file.txt](https://github.com/ElegantMonkey/mpv-webm/files/1883814/generated-with-log-file.txt)
[manual-command-piped.txt](https://github.com/ElegantMonkey/mpv-webm/files/1883819/manual-command-piped.txt)

**Comment by ElegantMonkey** [comment]
> [encode-lavc] no audio stream succeeded - invalid codec?

This line is interesting. Usually, when the encoding codec isn't available, I think it shows a different error.
`mpv --oac=help` should show the available audio codecs.

mpv-player/mpv#5666 seems to be somewhat related to this, at first sight.

**Comment by FlappyFalcon** [comment]
> I think what FlappyFalcon means by "not at a specific frame" is that it works on some videos when the section is like 00:10 to 00:20, but when you select 00:01 to 01:20 it fails. 00:10 to 00:20 actually works on the video I linked. But change it to 00:00 to 2:01 and it fails.

this is exactly what i meant, sorry for not specifying properly. at some time intervals it works, at others it doesn't

**Comment by ElegantMonkey** [comment]
Welp, this issue is getting kinda old, so I'd like to confirm if this still happens. mpv-player/mpv#5750 was supposed to fix this, but I still haven't gotten around testing.

**Comment by wingfixer** [comment]
Not sure if it's the same problem but I'm also not getting output after encoding youtube videos, no errors though. https://pastebin.com/C9aMzcCW

**Comment by FlappyFalcon** [comment]
I will close this now since I don't have this issue anymore since a long time ago, and was most likely something on mpv's end.
