### ISSUE TITLE
mpv-webm with mpv.net: `Command failed! Reason:  init`

### ISSUE THREAD

**Issue by soredake** [ekisu/mpv-webm#170]
## mpv version and platform
![Screenshot 2023-03-10 160547](https://user-images.githubusercontent.com/5204968/224336413-37dececc-356a-4d2f-8cb6-2a2423a3d180.png)

Windows 11

## Description

mpv-webm fails to encode saying  `Command failed! Reason:  init`

## Log file

[file.txt](https://github.com/ekisu/mpv-webm/files/10942752/file.txt)

**Comment by soredake** [comment]
Script works fine with regular mpv.

**Comment by soredake** [comment]
I can fix this error by changing mpv to mpvnet.exe
![image](https://github.com/ekisu/mpv-webm/assets/5204968/16717427-2444-4787-a042-c5beb7aaba57)

But now after encode nothing is saved on disk.

**Comment by po5** [comment]
libmpv frontends do not support encode mode, with the exception of [ImPlay](https://github.com/tsl0922/ImPlay).  
You must have regular mpv accessible within PATH.
