### ISSUE TITLE
Encode fails in GIF format

### ISSUE THREAD

**Issue by nikogang72** [ekisu/mpv-webm#177]
## mpv version and platform

(write OS and version)
Edition	Windows 10 Pro
Version	22H2
OS build	19045.3208
64 bit
```
paste output of "mpv --version" here.

mpv 0.35.0-579-gca4192e2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 01:30:52 2023
libplacebo version: v6.292.0-13-gf53badb-dirty
FFmpeg version: N-111598-gb2ceed406
FFmpeg library versions:
   libavutil       58.14.100
   libavcodec      60.22.100
   libavformat     60.10.100
   libswscale      7.3.100
   libavfilter     9.8.102
   libswresample   4.11.100
```
## Description

In every video format I tried, when I want to make a GIF (no matter what settings were chosen) the script starts encoding, but after some time it fails and says: "Encode failed! Check the log for details.".
This happened to me with an older version of the script, and with the lastest one, all the other output formats work (webm vp9, vp8, raw, hevc, mp3) but I can't make GIF work.

## Log file

https://pastebin.com/eyrpttac

**Comment by AymanAliS** [comment]
Soooooooo? You ever find a fix for that

**Comment by nikogang72** [comment]
> Soooooooo? You ever find a fix for that

Like a month ago I updated mpv, and since I updated it, I downloaded the script again and installed it, and it was fixed, maybe the problem were somewhere in my SO, or I don't know, but now it works

**Comment by AymanAliS** [comment]
Didn't work for me unfortunately so I'll just have to hold that
