### ISSUE TITLE
Lua error: <eof> expected near 'mp'

### ISSUE THREAD

**Issue by Soundtoxin** [ekisu/mpv-webm#178]
## mpv version and platform
Guix System GNU/Linux
guix (GNU Guix) be2344fbea00654c81218e8ecb6527fb53bd7639

```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg version: 6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

## Description

After updating webm.lua (grabbed the file from the README just a few minutes ago with `wget`) I get some warning/error output in my terminal that I did not before. Tested with some youtube videos. Command was this:
```
mpv 'https://www.youtube.com/watch?v=7vXGHl67_KE' 'https://www.youtube.com/watch?v=AAiNjRMy4Wo' 'https://www.youtube.com/watch?v=Ktce_i4qPFk' 'https://www.youtube.com/watch?v=sNgnwahAlzk' 'https://www.youtube.com/watch?v=DWr7CwZNEbE' 'https://www.youtube.com/watch?v=t48-FhXNmSo'
```

I overwrote my old webm.lua file so I don't recall how old it was.

edit: sha256sum of this particular webm.lua:
```
9c6ae4332f2b8dc4de716194c0bbded9c6b568800bbda0b7cee3919ff07e4718  ~/.config/mpv/scripts/webm.lua
```

## Log file

Attach the log file here. To generate a log file, you can add `log-file=log.txt` temporarily to your mpv.conf, or add `--log-file=log.txt` to the command line (it will be placed on the same location of the video file). You can use services like [pastebin](https://pastebin.com/) or similar ones to upload the file.

```
      webm:
      webm: stack traceback:
      webm:     [C]: in ?
      webm:     [C]: in ?
      webm: Lua error: ~/.config/mpv/scripts/webm.lua:2720: <eof> expected near 'mp'
```

[mpv-log_2023-09-27_19:26:44.txt](https://github.com/ekisu/mpv-webm/files/12744249/mpv-log_2023-09-27_19.26.44.txt)

**Comment by Soundtoxin** [comment]
`shift+w` appears to not bring up the controls anymore (does a panscan thing) so I suspect the script is currently not working at all.

The line 2720 from the error is the following:

```
 mp.get_property_native("vf")
```

**Comment by ekisu** [comment]
Maybe try downloading the script again? I've downloaded it from the link in the README, and I got this hash:
```sh
$ sha256sum webm.lua 
1704b826ba2711c280da0b13b6b5a052c72513fab064d9b9fec614268f893626  webm.lua
```

Please attach the script here, if this does not work

**Comment by Soundtoxin** [comment]
Works now! Interesting. Thanks. I may have done wget -c before in the scripts dir where the old one is, not sure if some sorta weird merge of the files could've take place. Though the line count was only a few lines different. Anyway, I moved that one out, grabbed the new one, and it worked straight away, so seems good now. Got the same hash as you this time as well. Closing.
