### ISSUE TITLE
Getting error: "AVFilterGraph: No such filter: 'fifo'"

### ISSUE THREAD

**Issue by Username9980** [ekisu/mpv-webm#189]
## mpv version and platform

mpv v0.37.0-663-g9cee4414 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Mar 22 2024 00:11:50
libplacebo version: v7.349.0 (v6.338.0-120-g7b29435-dirty)
FFmpeg version: N-114300-g535b1a93f
FFmpeg library versions:
   libavutil       59.3.100
   libavcodec      61.2.100
   libavformat     61.0.100
   libswscale      8.0.100
   libavfilter     10.0.100
   libswresample   5.0.100

## Description

This error happens when I try to encode into gif.

## Log file

[  51.452][e][webm] [ffmpeg] AVFilterGraph: No such filter: 'fifo'
[  51.452][e][webm] [ffmpeg] AVFilterGraph: Error creating filters
[  51.453][e][webm] [lavfi] parsing the filter graph failed
[  51.453][e][webm] [encode] no data written to target file
[  51.510][v][webm] Command stdout:  
[  51.510][v][webm] Exiting... (Interrupted by error)

**Comment by jack-mil** [comment]
Yep, I am getting the same issues recently. Here is my affected version (git build)

``` bash
❯ mpv --version
mpv v0.37.0-271-gf5c4f0b0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Feb 11 2024 00:11:11
libplacebo version: v6.338.0-77-g3ba18d5-dirty
FFmpeg version: N-113608-gafb630ce4
FFmpeg library versions:
   libavutil       58.36.101
   libavcodec      60.39.100
   libavformat     60.20.100
   libswscale      7.6.100
   libavfilter     9.17.100
   libswresample   4.13.100
   ```

**Comment by bepvte** [comment]
It was removed from FFMPEG its not needed anymore. Search webm.lua for `fifo` and comment out the line to fix it
