### ISSUE TITLE
Apply Current Video Filters doesn't work with sub-bold property

### ISSUE THREAD

**Issue by Hash6232** [ekisu/mpv-webm#191]
## mpv version and platform
```
mpv v0.38.0-63-gb364e4a6 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 21 2024 00:07:25
libplacebo version: v7.349.0 (v6.338.0-124-gd0eb997-dirty)
FFmpeg version: N-114900-ga44c34631
FFmpeg library versions:
   libavutil       59.15.100
   libavcodec      61.5.103
   libavformat     61.3.100
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```

## Description

For some reason the font style won't carry over when encoding to vp9. When using `sub-bold=yes` the font style correctly changes during playback but it won't affect the encoded video even if `Apply Current Video Filters` is active: https://mpv.io/manual/master/#options-sub-bold

## Log file

[log.txt](https://github.com/ekisu/mpv-webm/files/15139226/log.txt)

**Comment by mrfragger** [comment]
please add sub-blur (which works just fine when added to webm.lua as seen in bottom screenshot)

these are bugs with mpv encoder not webm
sub-border-style (background-box shown in screenshot doesn't work)...default is outline-and-shadow which obviously works

<img width="893" alt="image" src="https://github.com/user-attachments/assets/35d939c0-7db5-4f90-b388-ffdae190ba9a">


sub-align-y (bottom is default but center (shown in screenshot) and top don't apply
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/620dc296-40d6-42f3-a670-87ed49358450">

also sub-pos doesn't work either...will try to file bug with mpv encoder about these three sub options
