### ISSUE TITLE
Show a progress bar or some stats during the encoding

### ISSUE THREAD

**Issue by iiiGerardoiii** [ekisu/mpv-webm#30]
When you encode in ffmpeg, the CLI shows you some info during the encoding process. It would be nice to show some of that imo.

**Comment by iiiGerardoiii** [comment]
nvm I just realized the info is shown on mpv's CLI.
I always open mpv by double clicking the .exe, so when it's encoding I don't see any of it because I don't have the terminal open.

**Comment by ekisu** [comment]
The builtin `[statusline]` messages aren't very useful for indicating encode process, especially for short(er) clips, because they only indicate up to seconds. Maybe there's a way to make them more verbose, or report progress in some other way. I'll look at it.

**Comment by ekisu** [comment]
Could you try [this build](https://github.com/ekisu/mpv-webm/blob/display-progress/build/webm.lua)? It's a bit hacky, but it works (at least on Linux, haven't tried on other OSes).

**Comment by iiiGerardoiii** [comment]
> Could you try this build

Hmm, it can't encode with that build, gives me this error:
```Encode failed! Check logs for details```
I don't know where these logs are sorry for my ignorance.

I'm on Windows 10:
```$ mpv --version
mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.22.100
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: 4.1+809.g269daf5985

**Comment by ekisu** [comment]
Either add `log-file=log.txt` to your mpv.conf file or run it from a Terminal with `--log-file=log.txt`.

**Comment by iiiGerardoiii** [comment]
[log.txt](https://github.com/ekisu/mpv-webm/files/2408519/log.txt)
Hope that helps.

**Comment by ekisu** [comment]
Oops, there was a small typo. Unfortunately, it seems that there's no way to avoid a cmd popup on Windows when encoding...

**Comment by iiiGerardoiii** [comment]
Oh ok.

> it seems that there's no way to avoid a cmd popup on Windows when encoding...

I honestly don't mind, but I know there's people who would find that popup annoying :(

**Comment by jgreco** [comment]
> Could you try this build

Werks for me on OSX

**Comment by frozenpandaman** [comment]
This is a *huge* QOL improvement. Thank you for the suggestion and for implementing this!
