### ISSUE TITLE
Subtitle delay not taken into account

### ISSUE THREAD

**Issue by frozenpandaman** [ekisu/mpv-webm#36]
## mpv version and platform

Mac OS X 10.11.6
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Oct  7 04:03:13 PDT 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2
```

## Description

"Apply current video filters" disregards subtitle delay. I guess sub delay isn't considered a *video* track filter, really, so maybe this is intentional/expected behavior, technically speaking. Is there some way to have it take into account this setting during encoding?

**Comment by ekisu** [comment]
Should be fixed.

**Comment by frozenpandaman** [comment]
Yay, thanks! Will try it out tonight.
