### ISSUE TITLE
Encode failed

### ISSUE THREAD

**Issue by fpadova** [ekisu/mpv-webm#38]
## mpv version and platform

windows 10
```
mpv-x86_64-20190120-git-73fe061
```

## Description

Tried to make a webm with default options but after I try to encode it says that "Encode failed! Check the logs for details."

## Log file

https://pastebin.com/Fz9WJc3K

**Comment by ekisu** [comment]
Try using [this build](https://raw.githubusercontent.com/ekisu/mpv-webm/no-get-mpv-path/build/webm.lua) instead.

**Comment by fpadova** [comment]
> Try using [this build](https://raw.githubusercontent.com/ekisu/mpv-webm/no-get-mpv-path/build/webm.lua) instead.

Fixed. Thank you!
