### ISSUE TITLE
[Question] Change speed in the output file

### ISSUE THREAD

**Issue by ramblingdream** [ekisu/mpv-webm#42]
I find myself wanting to give a simple slowmo or quick effect to certain clips I make, is it possible to change the speed in the output file? If not could you add this feature, if possible of course, it would help a lot.

**Comment by ekisu** [comment]
Well, just adding the `--speed` flag to the encoder doesn't work. It produces files with broken timings when speed > 1, and it outright refuses to encode on speed < 1. I'll look if ffmpeg filters can do this.

**Comment by ramblingdream** [comment]
Thank you, one last thing I just remembered. Is it possible to add a naming variable that simply puts a number at the end of the output file in case there is another file with the same name in the directory? Sort of like how Windows does: (1), (2), (3)....

**Comment by ekisu** [comment]
@ramblingdream I would suggest you to create a different issue for that, but I don't really see an usecase for this.
