### ISSUE TITLE
Non ASCII characters in path

### ISSUE THREAD

**Issue by yutsuku** [ekisu/mpv-webm#43]
## mpv version and platform

```
Windows 10 Pro, Version 1083, Build 17134.648
mpv mpv-x86_64-20190310-git-1d0349d by shinchiro (no output from "mpv --version")
```

## Description

Currently the script is unable to output to same directory as file if the path contains non-ascii characters.

Tested with the following paths

```
E:\Video\pathtest\√\video.webm
E:\Video\pathtest\あ\video.webm
E:\Video\pathtest\Ą\video.webm
```

where
 `√` = `U+221A`
 `あ` = `U+3042`
 `Ą` = `U+0104`

## Excepted behavior

New files generated in following directories

```
E:\Video\pathtest\√\
E:\Video\pathtest\あ\
E:\Video\pathtest\Ą\
``` 

## Observed behavior

New files were generated in user folder

```
C:\users\moh\
```

## Log file

[mpvlog.txt](https://github.com/ekisu/mpv-webm/files/2972539/mpvlog.txt)

**Comment by ekisu** [comment]
Seems to be Windows-only, as it works fine for me on Ubuntu. Will take a look soon.

**Comment by ekisu** [comment]
See if [this build](https://raw.githubusercontent.com/ekisu/mpv-webm/283f3e302b4698daccdbd31238ec0ae14219d56e/build/webm.lua) works.

**Comment by yutsuku** [comment]
Works!
