### ISSUE TITLE
Problem encoding subtitles on vlive.tv

### ISSUE THREAD

**Issue by jamesxmcintosh** [ekisu/mpv-webm#46]
## mpv version and platform

kde neon 5.15
```
mpv git-2019-02-24-5370069 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Mar 10 00:58:59 UTC 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.47.102
   libavformat     58.26.101
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: git-2019-02-27-4571c7c

```

## Description

When streaming a video with multiple subtitle tracks, a different track than the one displayed is encoded.

example link
[https://www.vlive.tv/video/120131](https://www.vlive.tv/video/120131)

## Log file
[https://gist.github.com/jamesxmcintosh/c089f2521c849414318e0ae7a45908f6](https://gist.github.com/jamesxmcintosh/c089f2521c849414318e0ae7a45908f6)

**Comment by ekisu** [comment]
Can you test [this build](https://raw.githubusercontent.com/ekisu/mpv-webm/fca8e1c501bd3534c3dffa96e57eb2943469691c/build/webm.lua)?

**Comment by jamesxmcintosh** [comment]
Its fixed. Thanks
