### ISSUE TITLE
new template strings for filenames

### ISSUE THREAD

**Issue by bluefiberbread** [ekisu/mpv-webm#53]
would be nice if there were template strings for resolution too 

i.e. if I create a webm with "scale height" set to 720p, it'll include 720p in the filename

**Comment by ekisu** [comment]
Is the latest commit enough?

**Comment by bluefiberbread** [comment]
yeah but I can't activate the script with shift+w now

**Comment by bluefiberbread** [comment]
nvm I got it to work with shift+w script-binding webm/display-webm-encoder in input.conf

can it specify the resolution in the filename when default height is used too plz

**Comment by ekisu** [comment]
Added.
