### ISSUE TITLE
I can't drag my mouse on the osd

### ISSUE THREAD

**Issue by ChocoBar9** [ekisu/mpv-webm#57]
When I have the program in my scripts its not allowing me to use my mouse during playback. Is there a fix?

**Comment by ekisu** [comment]
Please don't ignore the [issue template](https://github.com/ekisu/mpv-webm/blob/master/.github/issue_template.md).

**Comment by ChocoBar9** [comment]
Please forgive me because I'm a complete novice when it comes to things like that. My issue is that while webm.lua is in my scripts folder I can't use my mouse to pause the video or move the cursor.

**Comment by ChocoBar9** [comment]
Gee all I ask is for some damn help and I get nothing.

**Comment by ekisu** [comment]
Uhh, I can't do anything if it works for me, and I don't have a single clue about what is happening on your system. At least submit your log file, please (add `log-file=log.txt` to your mpv.conf).

**Comment by ChocoBar9** [comment]
I'm doing that and nothing is happening.

**Comment by ekisu** [comment]
It should generate a log.txt file in the directory of the video file you're playing. If it doesn't, your mpv isn't reading your configuration correctly.

**Comment by ChocoBar9** [comment]
Alright I think I fixed it. I didn't put the src folder in.  Very sorry for being rude.

**Comment by norcalli** [comment]
@ChocoBar9 close issues when you have resolved your problem.
