### ISSUE TITLE
Script not working in the latest Windows10 

### ISSUE THREAD

**Issue by TasogareRiiku** [ekisu/mpv-webm#59]
## mpv version and platform
mpv-x86_64-20190707-git-c379950
(windows 10 1903 - 18362.239)

## Description
webm script is not working, I've downgraded to an older version and still no working

**Comment by ekisu** [comment]
Logs please.

**Comment by TasogareRiiku** [comment]
Sorry I don't know how to create logs

**Comment by TasogareRiiku** [comment]
I'm sorry, it's was just a hotkey problem on the input.conf, I'm really sorry

**Comment by ekisu** [comment]
It's alright. I'll be closing this then.
