### ISSUE TITLE
"%F" in filename when opening another file during encoding

### ISSUE THREAD

**Issue by frozenpandaman** [ekisu/mpv-webm#71]
## mpv version and platform
OS X 10.11.6
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Feb  4 16:12:56 PST 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1
```

## Description

While encoding is in progress, open another file in the same instance of mpv. The encoded/clipped output file filename contains `%F` rather than the replacing this with the actual source filename, e.g. produces an output file titled `%F-[10.40.039-15.42.974]-audio.mp4` (at least, I _think_ this opening-different-file-while-encoding-the-first is what makes this happen).

**Comment by ekisu** [comment]
I can't reproduce it. If you are/were using two pass, does the last commit fix your problem? There was a slight change on where the `format_filename` function is called.

**Comment by frozenpandaman** [comment]
Ah, I was using two-pass, yup! I'm guessing that was it, then. Can check for sure when I get back to my computer after traveling this weekend.
