### ISSUE TITLE
lavfi-colormatrix doesn't exist

### ISSUE THREAD

**Issue by horusra** [ekisu/mpv-webm#72]
## mpv version and platform
Latest MPV, Windows 10 Enterprise version 1809 build 17763.864
```
mpv 0.30.0-256-g61b8e1d436 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  1 19:21:15 +08 2019
ffmpeg library versions:
   libavutil       56.36.101
   libavcodec      58.64.101
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.67.100
   libswresample   3.6.100
ffmpeg version: git-2019-11-30-e5db2e96
```

## Description
nondescript error when I press "e" to convert.

![screenshot](https://user-images.githubusercontent.com/17074394/70363268-0bc06b00-1888-11ea-8864-144eccb106ce.jpg)

## Log file

[log file](https://files.catbox.moe/7ziv1q.txt)

**Comment by ekisu** [comment]
Fixed upstream in mpv-player/mpv@02d8d4e3
