### ISSUE TITLE
Encoding stays at 0% until completion

### ISSUE THREAD

**Issue by frozenpandaman** [ekisu/mpv-webm#73]
## mpv version and platform
macOS 10.14.6
```
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  3 20:28:56 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
```

## Description

Using the latest version of the script (eef451d). Encoding doesn't show progress, instead staying at 0% until it changes to the "Encoded successfully!" message. Happens always, from what I can tell – on different output formats, both two-pass and not, etc.

**Comment by ekisu** [comment]
Does [this](https://raw.githubusercontent.com/ekisu/mpv-webm/5675960c0f5490afce6ec5c3fd98b4f9f4b5e57b/build/webm.lua) work?

**Comment by frozenpandaman** [comment]
@ekisu Yup! Thanks!
