### ISSUE TITLE
lavfi-complex doesn't work

### ISSUE THREAD

**Issue by zonev3** [ekisu/mpv-webm#79]
## mpv version and platform
Windows 10 build 18363.720

mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015

## Description
I'm using lavfi-complex (--lavfi-complex='[aid1] [aid2] amix [ao]') to play 2 audio tracks at the same time, it works in mpv but after encoding the file only has 1 track

**Comment by ekisu** [comment]
Logs please.

**Comment by zonev3** [comment]
> Logs please.

[log.txt](https://github.com/ekisu/mpv-webm/files/4396629/log.txt) (hope this is the right one, if not let me know)
Here I used --lavfi-complex='[aid1] [aid2] amix [ao]' to play the game's audio and my mic's audio at the same time since they are recorded in different tracks, but when I use the script to make a small clip only the track that's currently selected is used

**Comment by ekisu** [comment]
Does [this build](https://raw.githubusercontent.com/ekisu/mpv-webm/7133e2c493a3077292dcb73b98659f054deb9617/build/webm.lua) work?

**Comment by zonev3** [comment]
> Does [this build](https://raw.githubusercontent.com/ekisu/mpv-webm/7133e2c493a3077292dcb73b98659f054deb9617/build/webm.lua) work?

Yes that's perfect, thanks. Obrigado.

**Comment by ekisu** [comment]
De nada 😅
