### ISSUE TITLE
Sluggish, probably stuck encoding

### ISSUE THREAD

**Issue by yutsuku** [ekisu/mpv-webm#82]
## mpv version and platform

Windows 10 v1903 (OS Build 18362.778)
```
mpv 0.32.0-320-gbca917f6d2 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Mar 29 16:28:52 +08 2020
FFmpeg library versions:
   libavutil       56.42.102
   libavcodec      58.77.101
   libavformat     58.42.100
   libswscale      5.6.101
   libavfilter     7.77.101
   libswresample   3.6.100
FFmpeg version: git-2020-03-29-4cb0dda55
```

## Description

For whatever reasons the script is extremely sluggish and/or stuck with [this - Chuunibyou demo Koi ga Shitai! Ren by Kametsu](https://anidb.net/group/11188/anime/9874/release) (or more) specific release. The script is working fine with my other files.
I am not sure if this is mpv fault, script fault or encoders' fault (file plays normally in mpv).

## Log file
[mpv.log](https://github.com/ekisu/mpv-webm/files/4581186/mpv.log)

**Comment by ekisu** [comment]
```
[ 320.004][v][webm]  Title: [Kametsu] Love, Chunibyo & Other Delusions-Heart Throb - 02v2 [BD1080p][Hi10][Dual]
[ 320.004][v][webm] [ao/lavc] Opening encoder: libvorbis [libvorbis]
[ 320.004][v][webm] AO: [lavc] 48000Hz stereo 2ch floatp
[ 320.004][v][webm] VO: [lavc] 854x480 => 854x480 yuv420p
[ 320.004][v][webm] [vo/lavc] Opening encoder: libvpx VP8 [libvpx]
[ 320.004][v][webm] [encode] Opening output file: ./[Kametsu] Chuunibyou demo Koi ga Shitai! Ren - 02v2 (1920x1080 h264 BD FLAC'FLAC) [BE335A93]-[15.12.745-15.31.097]-audio.webm
[ 320.004][v][webm] [encode] Opening muxer: WebM [webm]
[ 320.004][v][webm] [ao/lavc] audio frame pts went backwards (541440 <- 11280), autofixed
[ 320.004][v][webm] [ao/lavc] audio frame pts went backwards (541488 <- 11281), autofixed
[ 320.004][v][webm] [ao/lavc] audio frame pts went backwards (541536 <- 11282), autofixed
.. removed (910848) repeating messages ..
[ 325.388][v][webm] [ao/lavc] audio frame pts went backwards (44262288 <- 922131), autofixed
[ 325.388][v][webm] [ao/lavc] audio frame pts went backwards (44262336 <- 922132), autofixed
[ 325.388][v][webm] [ao/lavc] audio frame pts went backwards (44262384 <- 922133), autofixed
[ 325.388][v][webm] [ao/lavc] audio frame pts went backwards (44262432 <- 922134), autofixed
```

Seems like a broken file, I guess. You should probably report this to the mpv repo itself. Here's the command line if you want to reproduce the issue without using this script (you could drop a lot of the options, and the parameter escaping is probably borked, but it might help a bit):

`mpv "./[Kametsu] Chuunibyou demo Koi ga Shitai! Ren - 02v2 (1920x1080 h264 BD FLAC'FLAC) [BE335A93].mkv" --start=0:15:12.745 --end=0:15:31.097 --ovc=libvpx --oac=libvorbis --loop-file=no --aid=2 --vid=1 --sid=2 --sub-ass-override=yes --sub-auto=fuzzy --sub-delay=0.000000 --video-rotate=0 --vf-add=lavfi-colormatrix=bt709:bt601 --vf-add=lavfi-scale=-2:480 --ovcopts-add=threads=4 "--oset-metadata=title=%92%[Kametsu] Chuunibyou demo Koi ga Shitai! Ren - 02v2 (1920x1080 h264 BD FLAC'FLAC) [BE335A93]" --ovcopts-add=b=8718k "-o=./[Kametsu] Chuunibyou demo Koi ga Shitai! Ren - 02v2 (1920x1080 h264 BD FLAC'FLAC) [BE335A93]-[15.12.745-15.31.097]-audio.webm"`

**Comment by yutsuku** [comment]
Looks like it was fixed before I even updated mpv, thanks for looking into it.
No issues with it with the following mpv version:
```
mpv 0.32.0-410-g640db1ed3f Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 26 14:33:34 +08 2020
FFmpeg library versions:
   libavutil       56.43.100
   libavcodec      58.82.100
   libavformat     58.42.101
   libswscale      5.6.101
   libavfilter     7.79.100
   libswresample   3.6.100
FFmpeg version: git-2020-04-25-cca0436ef
```

**Comment by ekisu** [comment]
Well, I'm happy it fixed itself..? Anyway, I'll close this then, feel free to reopen if the problem appears again.
