### ISSUE TITLE
Option to encode audio only

### ISSUE THREAD

**Issue by Yzuriha** [ekisu/mpv-webm#85]
As the title stats, I'm wondering if its possible to add an option to encode the audio only instead of the whole video.

**Comment by po5** [comment]
The script uses whatever tracks are selected, simply disable the video track.

**Comment by Yzuriha** [comment]
Disabling the video will still encode it as MP4 or WEBM for example. I'm wondering whether it is possible to receive like a MP3.

**Comment by a-vrma** [comment]
You can remux or re encode using `ffmpeg`.

**Comment by ekisu** [comment]
Does [this](https://raw.githubusercontent.com/ekisu/mpv-webm/89ae93b8823d566f9e4bc42bdf4be097c162e227/build/webm.lua) work?

**Comment by Yzuriha** [comment]
Works perfectly! Thanks you very much!
