### ISSUE TITLE
no audio on output

### ISSUE THREAD

**Issue by kindreddd** [ekisu/mpv-webm#89]
## mpv version and platform

(write OS and version)
```
mpv 0.32.0-563-gdc24a437fb Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 21 22:18:57 +08 2020
FFmpeg library versions:
   libavutil       56.55.100
   libavcodec      58.93.100
   libavformat     58.47.100
   libswscale      5.8.100
   libavfilter     7.86.100
   libswresample   3.8.100
FFmpeg version: git-2020-06-21-842bc312a

OS: Windows 10
```

## Description

Every WEBm output has video but no audio even with the sound unmuted. I'm not sure what's making this happen.

## Log file

[log.txt](https://github.com/ekisu/mpv-webm/files/4864158/log.txt)

**Comment by snow344** [comment]
This is also happening to me with both WEBM and MP4 files.

**Comment by FilthyLiquid** [comment]
Same here, but I'm using the FFmpeg version.

**Comment by ekisu** [comment]
Managed to reproduce on Windows 10 with Shinchiro's builds, I'll try building it to see what's going on - there are some weird generic errors on the log, probably something with FFmpeg or idk
```
[  15.787][v][webm] [ao/lavc] error encoding at -2.26757e-05
[  15.787][v][webm] [ao/lavc] error encoding at 0.00142857
[  15.787][v][webm] [ao/lavc] error encoding at 0.00287982
[  15.787][v][webm] [ao/lavc] error encoding at 0.00433107
(repeat for like every frame)
```

@FilthyLiquid FFmpeg version and OS, please. This is pretty weird, although I'm almost sure it's something upstream (as it's breaking on both at the same time)

**Comment by FilthyLiquid** [comment]
> 
> 
> Managed to reproduce on Windows 10 with Shinchiro's builds, I'll try building it to see what's going on - there are some weird generic errors on the log, probably something with FFmpeg or idk
> 
> ```
> [  15.787][v][webm] [ao/lavc] error encoding at -2.26757e-05
> [  15.787][v][webm] [ao/lavc] error encoding at 0.00142857
> [  15.787][v][webm] [ao/lavc] error encoding at 0.00287982
> [  15.787][v][webm] [ao/lavc] error encoding at 0.00433107
> (repeat for like every frame)
> ```
> 
> @FilthyLiquid FFmpeg version and OS, please. This is pretty weird, although I'm almost sure it's something upstream (as it's breaking on both at the same time)

Windows 10 64bit
ffmpeg version git-2020-06-28-4cfcfb3

**Comment by Reberebe** [comment]
I'm having the same issue, both with Webm and MP4 
If I try exporting an MP3 it exports an empty file

**Comment by ekisu** [comment]
Fixed upstream, should (eventually) be fixed on Windows binaries or something
