### ISSUE TITLE
Framerate options?

### ISSUE THREAD

**Issue by wantija** [ekisu/mpv-webm#95]
Is there any possibility to add an option to reduce the framerate of videos with this? It can greatly reduce filesize when going from 60fps to 30 or 24. [Standalone .webm creators](https://gitgud.io/nixx/WebMConverter) have this option so it would be very convenient if this were added.

**Comment by ekisu** [comment]
Does [this](https://raw.githubusercontent.com/ekisu/mpv-webm/68e65d4759bac26a3fbde3af291162153431f67c/build/webm.lua) build work?

**Comment by wantija** [comment]
Unfortunately it didn't work, Here's the log: https://pastebin.com/dV9ky3iR

**Comment by ekisu** [comment]
Weird, the error seems completely unrelated to the FPS option:
```
[vo/lavc] codec for video not found
```

Does it work with the older build (without the FPS option)?

**Comment by wantija** [comment]
Alright so I was using the latest mpv-build-git from the AUR, went back to mpv 0.32 and it works. Also tried it on Windows with an earlier git version and it works there, so it must've been an mpv or ffmpeg regression?

**Comment by ekisu** [comment]
Probably the build you used didn't enable the correct flags for using the encoding codecs, they kinda need to be enabled separately. Well, I'll merge and close this, then.
